# This file was generated by GoReleaser. DO NOT EDIT.
cask "version-check-mcp" do
  version "0.0.3"

  on_macos do
    on_intel do
      sha256 "23d7665126fc2bfe0153dc1db3182f9099836af40528286466c847fe289f6dbd"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55ecc6d5d6e3cc121259864f11a4982402f48c0c8ba70266dc3ce50a30bb370b"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3ba8f48a402f3f5fa91c85c38e0ffcc5c60df546d77afefb9b125500c275ee6b"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a31a071d2467776b0d1614b009bf796db343d48a972fc6290a70e167d939d6df"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "version-check-mcp"
  desc "Lightweight MCP server giving AI coding agents a single source of truth for software package versions"
  homepage "https://github.com/JesperRossen/version-check-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "version-check-mcp"

  # No zap stanza required

end
