# This file was generated by GoReleaser. DO NOT EDIT.
cask "version-check-mcp" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "a5c1ed80cef8d84240044763b2f0939b76e76c633b084af7dddaa3a9b25b857e"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7e66e6b095a5c04af3cd2b5fe4caac0e4ae0099f346de836bc09cdfbc64b1106"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f77d86b1a406a80d7211357f2ffc6ba65e0d1fb1aa53d00efb77d31fd1105f45"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "52e6d5b07ed081035b093b1d6d6e9f259b8743630b7b5e6e4bb99727a0ed6bf9"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "version-check-mcp"
  desc "Lightweight MCP server giving AI coding agents a single source of truth for software package versions"
  homepage "https://github.com/JesperRossen/version-check-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "version-check-mcp"

  # No zap stanza required

end
