# This file was generated by GoReleaser. DO NOT EDIT.
cask "version-check-mcp" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "ef6855a160226b1139ac36d417bab408a089412914e92257036608da961cb9da"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b48bf0ae04e60e5e2931254399a6a76f5aa189ed0ab6e4a89b6f582266a1f736"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4d22c8a383c511bbf6d64e87501e61f642262cb4dffd6613c2d5db5265f46327"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6c04c9fe5f1a28f10468ab415403be90fefe6401eae92142e562f42b0c0f758"
      url "https://github.com/JesperRossen/version-check-mcp/releases/download/v#{version}/version-check-mcp_#{version}_linux_arm64.tar.gz"
    end
  end

  name "version-check-mcp"
  desc "Lightweight MCP server giving AI coding agents a single source of truth for software package versions"
  homepage "https://github.com/JesperRossen/version-check-mcp"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "version-check-mcp"

  # No zap stanza required

end
